express = require('express')
config = require('./config')()
require('./config/models')
app = express()
redis = require('./config/redis')(config.redis)
app.mongoose = require('./config/mongoose')(config.mongo)
app.pusher = require('./config/pusher')()
app.passport = require('./config/passport')(app.mongoose)
require('./config/express')(app, app.passport)
require('./config/routes')(app, redis)
