# TODO - refactor to make data set a param

@services.factory "country", () ->
  {
      "AC":"Ascension Island"
      "AF":"Afghanistan"
      "AX":"Aland"
      "AL":"Albania"
      "DZ":"Algeria"
      "AD":"Andorra"
      "AO":"Angola"
      "AI":"Anguilla"
      "AQ":"Antarctica"
      "AG":"Antigua And Barbuda"
      "AR":"Argentina Republic"
      "AM":"Armenia"
      "AW":"Aruba"
      "AU":"Australia"
      "AT":"Austria"
      "AZ":"Azerbaijan"
      "BS":"Bahamas"
      "BH":"Bahrain"
      "BD":"Bangladesh"
      "BB":"Barbados"
      "BY":"Belarus"
      "BE":"Belgium"
      "BZ":"Belize"
      "BJ":"Benin"
      "BM":"Bermuda"
      "BT":"Bhutan"
      "BO":"Bolivia"
      "BA":"Bosnia And Herzegovina"
      "BW":"Botswana"
      "BV":"Bouvet Island"
      "BR":"Brazil"
      "IO":"British Indian Ocean Terr"
      "VG":"British Virgin Islands"
      "BN":"Brunei Darussalam"
      "BG":"Bulgaria"
      "BF":"Burkina Faso"
      "BI":"Burundi"
      "KH":"Cambodia"
      "CM":"Cameroon"
      "CA":"Canada"
      "CV":"Cape Verde"
      "KY":"Cayman Islands"
      "CF":"Central African Republic"
      "TD":"Chad"
      "CL":"Chile"
      "CN":"People\u2019S Republic Of China"
      "CX":"Christmas Islands"
      "CC":"Cocos Islands"
      "CO":"Colombia"
      "KM":"Comoras"
      "CG":"Congo"
      "CD":"Congo (Democratic Republic)"
      "CK":"Cook Islands"
      "CR":"Costa Rica"
      "CI":"Cote D Ivoire"
      "HR":"Croatia"
      "CU":"Cuba"
      "CY":"Cyprus"
      "CZ":"Czech Republic"
      "DK":"Denmark"
      "DJ":"Djibouti"
      "DM":"Dominica"
      "DO":"Dominican Republic"
      "TP":"East Timor"
      "EC":"Ecuador"
      "EG":"Egypt"
      "SV":"El Salvador"
      "GQ":"Equatorial Guinea"
      "EE":"Estonia"
      "ET":"Ethiopia"
      "FK":"Falkland Islands"
      "FO":"Faroe Islands"
      "FJ":"Fiji"
      "FI":"Finland"
      "FR":"France"
      "FX":"France Metropolitan"
      "GF":"French Guiana"
      "PF":"French Polynesia"
      "TF":"French Southern Territories"
      "GA":"Gabon"
      "GM":"Gambia"
      "GE":"Georgia"
      "DE":"Germany"
      "GH":"Ghana"
      "GI":"Gibralter"
      "GR":"Greece"
      "GL":"Greenland"
      "GD":"Grenada"
      "GP":"Guadeloupe"
      "GU":"Guam"
      "GT":"Guatemala"
      "GN":"Guinea"
      "GW":"Guinea Bissau"
      "GY":"Guyana"
      "HT":"Haiti"
      "HM":"Heard & Mcdonald Island"
      "HN":"Honduras"
      "HK":"Hong Kong"
      "HU":"Hungary"
      "IS":"Iceland"
      "IN":"India"
      "ID":"Indonesia"
      "IR":"Iran
       Islamic Republic Of"
      "IQ":"Iraq"
      "IE":"Ireland"
      "IM":"Isle Of Man"
      "IL":"Israel"
      "IT":"Italy"
      "JM":"Jamaica"
      "JP":"Japan"
      "JO":"Jordan"
      "KZ":"Kazakhstan"
      "KE":"Kenya"
      "KI":"Kiribati"
      "KP":"Korea
       Dem. Peoples Rep Of"
      "KR":"Korea
       Republic Of"
      "KW":"Kuwait"
      "KG":"Kyrgyzstan"
      "LA":"Lao People\u2019S Dem. Republic"
      "LV":"Latvia"
      "LB":"Lebanon"
      "LS":"Lesotho"
      "LR":"Liberia"
      "LY":"Libyan Arab Jamahiriya"
      "LI":"Liechtenstein"
      "LT":"Lithuania"
      "LU":"Luxembourg"
      "MO":"Macao"
      "MK":"Macedonia"
      "MG":"Madagascar"
      "MW":"Malawi"
      "MY":"Malaysia"
      "MV":"Maldives"
      "ML":"Mali"
      "MT":"Malta"
      "MH":"Marshall Islands"
      "MQ":"Martinique"
      "MR":"Mauritania"
      "MU":"Mauritius"
      "YT":"Mayotte"
      "MX":"Mexico"
      "FM":"Micronesia"
      "MD":"Moldava Republic Of"
      "MC":"Monaco"
      "MN":"Mongolia"
      "ME":"Montenegro"
      "MS":"Montserrat"
      "MA":"Morocco"
      "MZ":"Mozambique"
      "MM":"Myanmar"
      "NA":"Namibia"
      "NR":"Nauru"
      "NP":"Nepal"
      "AN":"Netherlands Antilles"
      "NL":"Netherlands
       The"
      "NC":"New Caledonia"
      "NZ":"New Zealand"
      "NI":"Nicaragua"
      "NE":"Niger"
      "NG":"Nigeria"
      "NU":"Niue"
      "NF":"Norfolk Island"
      "MP":"Northern Mariana Islands"
      "NO":"Norway"
      "OM":"Oman"
      "PK":"Pakistan"
      "PW":"Palau"
      "PS":"Palestine"
      "PA":"Panama"
      "PG":"Papua New Guinea"
      "PY":"Paraguay"
      "PE":"Peru"
      "PH":"Philippines (Republic Of The)"
      "PN":"Pitcairn"
      "PL":"Poland"
      "PT":"Portugal"
      "PR":"Puerto Rico"
      "QA":"Qatar"
      "RE":"Reunion"
      "RO":"Romania"
      "RU":"Russian Federation"
      "RW":"Rwanda"
      "WS":"Samoa"
      "SM":"San Marino"
      "ST":"Sao Tome/Principe"
      "SA":"Saudi Arabia"
      "UK":"United Kingdom"
      "SN":"Senegal"
      "RS":"Serbia"
      "SC":"Seychelles"
      "SL":"Sierra Leone"
      "SG":"Singapore"
      "SK":"Slovakia"
      "SI":"Slovenia"
      "SB":"Solomon Islands"
      "SO":"Somalia"
      "AS":"Somoa
      Gilbert
      Ellice Islands"
      "ZA":"South Africa"
      "GS":"South Georgia
       South Sandwich Islands"
      "SU":"Soviet Union"
      "ES":"Spain"
      "LK":"Sri Lanka"
      "SH":"St. Helena"
      "KN":"St. Kitts And Nevis"
      "LC":"St. Lucia"
      "PM":"St. Pierre And Miquelon"
      "VC":"St. Vincent & The Grenadines"
      "SD":"Sudan"
      "SR":"Suriname"
      "SJ":"Svalbard And Jan Mayen"
      "SZ":"Swaziland"
      "SE":"Sweden"
      "CH":"Switzerland"
      "SY":"Syrian Arab Republic"
      "TW":"Taiwan"
      "TJ":"Tajikistan"
      "TZ":"Tanzania
       United Republic Of"
      "TH":"Thailand"
      "TG":"Togo"
      "TK":"Tokelau"
      "TO":"Tonga"
      "TT":"Trinidad And Tobago"
      "TN":"Tunisia"
      "TR":"Turkey"
      "TM":"Turkmenistan"
      "TC":"Turks And Calcos Islands"
      "TV":"Tuvalu"
      "UG":"Uganda"
      "UA":"Ukraine"
      "AE":"United Arab Emirates"
      "GB":"United Kingdom (No New Registrations)"
      "US":"United States"
      "UM":"United States Minor Outl.Is."
      "UY":"Uruguay"
      "UZ":"Uzbekistan"
      "VU":"Vanuatu"
      "VA":"Vatican City State"
      "VE":"Venezuela"
      "VN":"Viet Nam"
      "VI":"Virgin Islands (Usa)"
      "WF":"Wallis And Futuna Islands"
      "EH":"Western Sahara"
      "YE":"Yemen"
      "ZM":"Zambia"
      "ZW":"Zimbabwe"
  }